name: remote ssh command
on: [push]
env:
  ENV_FILE: ${{ secrets.ENV_FILE }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          echo "${{ secrets.ENV_FILE }}" >> .env
          git clone "${{ github.repositoryUrl }}"
          docker compose down
          docker compose up -d
